development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: thinkmeter_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: thinkmeter_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: thinkmeter_production
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
